name: network_tools
description: Networking Tools library which can help you discover open ports, devices on subnet and many other things. 
version: 1.0.7
issue_tracker: https://github.com/git-elliot/network_tools/issues
documentation: https://pub.dev/documentation/network_tools/latest
repository: https://github.com/git-elliot/network_tools
homepage: https://github.com/git-elliot/network_tools

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_ping: ^6.1.1
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.8.2
  test: ^1.20.1
