name: network_tools
description: Networking Tools library which can help you discover open ports, devices on subnet and many other things. 
version: 0.0.6
issue_tracker: https://github.com/git-elliot/network_tools/issues
documentation: https://pub.dev/documentation/network_tools/latest
repository: https://github.com/git-elliot/network_tools
homepage: https://github.com/git-elliot/network_tools

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_ping: ^6.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
